seoecho_homepage:
    path:     /
    defaults: { _controller: echoSEOBundle:Default:index }

seoecho_validFormMcUrl:
    path:     /validFormMcUrl
    defaults: { _controller: echoSEOBundle:Default:validFormMcUrl }

seoecho_refreshEcho:
    path:     /refreshEcho
    defaults: {_controller: echoSEOBundle:Echo:refresh }

seoecho_apprentissageEcho:
    path:     /apprentissageEcho
    defaults: { _controller: echoSEOBundle:Echo:apprentissage }
