services:
    echov:
        class: SEOecho\echoSEOBundle\Services\Echov
        arguments:
        - "@service_container"

    echos:
        class: SEOecho\echoSEOBundle\Services\Echos
        arguments:

    echobt:
        class: SEOecho\echoSEOBundle\Services\Echobt
        arguments:

    smithwatermangotoh:
        class: SEOecho\echoSEOBundle\Services\SmithWatermanGotoh
        arguments:

    jarowinkler:
        class: SEOecho\echoSEOBundle\Services\JaroWinkler
        arguments:
